
drop schema GENERIF RESTRICT;
create schema GENERIF;
set schema GENERIF;

drop INDEX GENERIF_ASSOC_INDEX1;
drop INDEX GENERIF_ASSOC_INDEX2;

drop table ASSOCIATION;
create table ASSOCIATION
	(
	id INT not null primary key , --GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),  
	geneId INT not null,
	title clob,
	pmids varchar(60) not null,
	umls varchar(60) not null,
	doid varchar(20) not null
	);

create index GENERIF_ANNOT_INDEX1  ON ASSOCIATION(doid);
create index GENERIF_ANNOT_INDEX2  ON ASSOCIATION(geneId);

