
drop schema JENSENLAB RESTRICT;
create schema JENSENLAB;
set schema JENSENLAB;

drop INDEX JENSENLAB_ASSOC_INDEX1;
drop INDEX JENSENLAB_ASSOC_INDEX2;
drop INDEX JENSENLAB_ASSOC_INDEX3;

drop table ASSOCIATION;
create table ASSOCIATION
	(
	id INT not null primary key , --GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),  
	ensemblProt varchar(20) not null,
	genesymbol varchar(60) not null,
	doid varchar(20) not null,
	description varchar(100)  not null,
	z_score double not null,
	condidence double not null
	);

create index JENSENLAB_ANNOT_INDEX1  ON ASSOCIATION(doid);
create index JENSENLAB_ANNOT_INDEX2  ON ASSOCIATION(genesymbol);
create index JENSENLAB_ANNOT_INDEX3 ON ASSOCIATION(ensemblProt);

