drop schema NCBI RESTRICT;
create schema NCBI;
set schema NCBI;

drop INDEX NCBI_NAME2GENEIDX1;
ALTER TABLE NAME2GENE DROP CONSTRAINT NCBI_NAME2GENEID_FK1;


drop table GENE;
create table GENE
	(
	id INT not null primary key , --GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),  
	gzcontent blob
	);

drop table NAME2GENE;
create table NAME2GENE
	(
	id INT not null primary key, -- GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),  
	gene_id INT not null  ,
	name varchar(50) not null ,
	CONSTRAINT NCBI_NAME2GENEID_FK1 FOREIGN KEY(gene_id) REFERENCES GENE(id),
	);
delete from NAME2GENE;

create UNIQUE index NCBI_NAME2GENEIDX1  ON NAME2GENE(name);





